repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    - id: check-yaml
    - id: no-commit-to-branch
      args: [-b, main]
    - id: check-json
    - id: trailing-whitespace
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
    - id: terraform_validate
      args:
        - --tf-init-args=-backend=false
    - id: terraform_fmt
    - id: terraform_checkov
      args:
      - --args=--skip-check CKV2_GHA_1 --skip-path image # skipping check on workflow permissions for now, checkov does not have packer support so throws an error trying to read packer files
    - id: terraform_tflint